name: Lint and Testing

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --verbose

      - uses: hadolint/hadolint-action@v3.1.0
        name: hadolint for Dockerfile
        with:
          dockerfile: docker/Dockerfile

  testing:
    runs-on: ubuntu-latest
    container: golang:1.21-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup related tools
        run: |
          apk add make build-base zlib-dev ucl-dev

      - name: testing
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
